Feature/#6-회원가입 구현
f-lab-edu/Online-Market pull request #7
Opened 2023-12-27 20:04 UTC by dnzp75

**회원가입에 기능 구현에 따른 코드 작성** 

- User controller,service Test 코드 작성

- SHA256 알고리즘을 이용한 비밀번호 암호화 구현
-> Spring Security 사용하여 간단하게 구현할 수 있었지만 학습을 목표로 구현 로직이 복잡한 SHA256 알고리즘 사용하여 구현 

- 이메일 중복 검사 구현
-> emailCheck 메서드를 통해 구현

2023-12-28 22:05 UTC, f-lab-jason requested changes
테스트 관련해서는 세션때 얘기한것처럼 조금 더 여러 케이스가 있으면 좋겠습니다 🙂

2023-12-28 22:05 UTC, f-lab-jason commented on src/main/java/com/example/onlinemarket/utils/SHA256Util.java
> +    public static String encryptSHA256(String str) {
로컬 변수와 메소드 시작 사이엔 한 줄 띄워주세요

2023-12-28 22:05 UTC, f-lab-jason commented on src/main/java/com/example/onlinemarket/utils/SHA256Util.java
> +    public static final String ENCRYPTION_TYPE = "SHA-256";
왜 public인가요?

2023-12-28 22:05 UTC, f-lab-jason commented on src/main/java/com/example/onlinemarket/utils/SHA256Util.java
> +@Log4j2
import와 클래스 사이도 한 줄 띄워주세요

2023-12-28 22:05 UTC, f-lab-jason commented on src/main/java/com/example/onlinemarket/utils/SHA256Util.java
> +        MessageDigest sh;
이 친구는 왜 try 밖에 있나요?

2023-12-28 22:05 UTC, f-lab-jason commented on src/main/java/com/example/onlinemarket/utils/SHA256Util.java
> +        String SHA = null;
1. 로컬변수를 upper case로 작성하신 이유가 있나요?
2. 변수 이름은 왜 SHA인가요? 여기서 리턴하는건 '암호화된 문자열'인데 SHA(=secure hash algorithm)라는 이름은 이상해보여요
3. 애초에 try안에서 쓰는 `StringBuilder`를 선언해놓고 쓰는게 더 좋아보이는데 어떻게 생각하시나요?

2024-01-09 22:00 UTC, f-lab-jason commented on src/main/java/com/example/onlinemarket/domain/user/mapper/UserMapper.java
> +    int existsByEmail(String email);
nit: `emailExists`

2024-01-10 14:20 UTC, dnzp75 commented
#6 - 회원가입 구현 3차 리팩토링

-  한 줄로 작성 했었던 코드들 formatter 적용하여 재 수정
-  SHA256Util 클래스 encryptedSring 변수 제거
-  existByEmail -> emailExists 메소드명 알맞게 변경
- EncryptedPassword -> encryptedPassword 암호화된 비밀번호 메소드 변경
- SHA256UtilTest 테스트 코드 작성

2024-01-11 13:57 UTC, merged